### ISSUE TITLE
train_val_split函数问题

### ISSUE THREAD

**Issue by chenxinst** [HC-Feynman/vpu#1]
dataset/dataset_cifar.py文件中train_val_split函数37行，train_unlabeled_idxs.extend(idxs[0:-500])，为什么在训练集unlabel数据中同时也包含了labeled数据？36行train_labeled_idxs.extend(idxs[:n_labeled_per_class])，显然train_unlabeled_idxs是包含train_labeled_idxs的，请问这里有什么trick吗？

**Comment by HC-Feynman** [comment]
Yes, in the experiments we treat the positive data as part of the unlabeled data.
(1) This does not break the theoretical correctness.
(2) This is done for all methods in the experiments. The comparison is fair.
(3) My experience tells me this does not make a big difference to VPU.

**Comment by chenxinst** [comment]
So, why you must treat the positive data as part of the unlabeled data? What will happen if we don't apply this treatment to any method? Intuitively，this treatment just decreases the performence of other baselines.

**Comment by HC-Feynman** [comment]
In theory, there are two scenarios in PU learning. One is called the single-training-set scenario, where samples in $P \cup U$ are drawn from $f$, and the other is called the case-control where samples in $P$ and $U$ are drawn from $f_P$ and $f$ independently. Take CIFAR as an example, the 50000 samples of CIFAR training set represent $f$. Each of the 50000 samples are drawn from $f$ iid, so the CIFAR training set is by nature of the single-training-set scenario. The 3000 so-called positive samples are manually assigned, not independently generated. So in this sense, in theory we should count all 50000  samples as unlabeled, since the rest 47000 samples cannot represent what we really learn about $f$ from the CIFAR training set.  In practice, as in the CIFAR example, the so-called positive set has only 3000, which is small compared to 50000, so putting $P$ into $U$ does not really make a difference to the empirical distribution of $f$.

Based on the analysis above, I come back to your questions:

“So, why you must treat the positive data as part of the unlabeled data?” 
--------- We should do it, as explained above: "the rest 47000 samples cannot represent what we really learn about $f$ from the CIFAR training set". The difference is trivial if $P$ is relatively small, so in practice it is not a must-do thing.

"What will happen if we don't apply this treatment to any method?"
--------- No big difference for any method in my experiments.

"Intuitively，this treatment just decreases the performance of other baselines."
--------- Could you explain why?

**Comment by chenxinst** [comment]
I would like to apologize for my offence. I found my mistake after researching the relevant literature and carefully reading your paper.
