### ISSUE TITLE
Could you please give me a proof of Proposition 12 at your convenience?

### ISSUE THREAD

**Issue by Hengwei-Zhao96** [HC-Feynman/vpu#3]
Could you please give me a proof of Proposition 12 at your convenience? 
Proposition 12: If Assumption 2 is satisfied and supx Φ(x) = 1 for a function Φ : Rd → [0, 1], Lvar(Φ) = Lvar(Φ∗) iffΦ = Φ∗.

**Comment by Hengwei-Zhao96** [comment]
Excuse me, is because supx Φ (x) = 1, so c = 1?

**Comment by Hengwei-Zhao96** [comment]
So let me ask if I could understand proposition 12 this way?

The distribution of P is not a subset of N and The maximum value of Φ (x) is 1, Lvar(Φ) = Lvar(Φ∗) iff Φ = Φ∗?

Sorry, I have a lot of questions, and looking forward to your reply.

**Comment by HC-Feynman** [comment]
"Excuse me, is because supx Φ (x) = 1, so c = 1?  "
----------------------- Correct.

"The distribution of P is not a subset of N and The maximum value of Φ (x) is 1, Lvar(Φ) = Lvar(Φ∗) iff Φ = Φ∗?"
-----------------------Basically correct. 
You may understand it this way: 
The support of f_P is not a subset of that of f_N; In other words, there is some part of supp(f_P) on which f_N = 0, which means this part can only be positive, which means Φ∗ = 1 on this part. So the maximum value of Φ∗ is 1. 
Then the iff statement in Prop. 12 should be proved in both directions. 
(1) From " Lvar(Φ) = Lvar(Φ∗)"  to "Φ = Φ∗" : Lvar(Φ) = Lvar(Φ∗) tells us, according to Prop. 11, Φ = c Φ∗. But we already know that max Φ = max Φ∗ =1, so c=1, so Φ = Φ∗.
(2) From "Φ = Φ∗" to "Lvar(Φ) = Lvar(Φ∗)"  : Plug c=1 into Prop. 11 we can directly get this result.

**Comment by Hengwei-Zhao96** [comment]
Sincerely thank you for your reply！
